local dir=debug.getinfo(1,'S').source:sub(2):match('^(.*)/')
local R=reaper
local current,path=R.EnumProjects(-1,'')
if path==dir..'/Tuner preview.rpp' then
 R.OnStopButton()
 local track=R.GetTrack(0,0)
 local f=assert(io.open(dir..'/preview-controls.txt','w'))
 for i=0,7 do local _,name=R.TrackFX_GetParamName(track,0,i);f:write(name..'='..R.TrackFX_GetParam(track,0,i)..'\n') end
 f:close()
 R.Main_SaveProjectEx(current,path,8)
 R.Main_OnCommand(40860,0)
 return
end
assert(R.GetPlayState()==0,'Stop before opening the silent tuner preview.')
R.Main_OnCommand(41929,0)
local project=R.EnumProjects(-1,'')
R.InsertTrackAtIndex(0,false)
local track=R.GetTrack(0,0)
R.GetSetMediaTrackInfo_String(track,'P_NAME','Generated A2 - silent preview',true)
R.SetMediaTrackInfo_Value(track,'I_RECARM',0)
R.SetMediaTrackInfo_Value(track,'I_RECMON',0)
local master=R.GetMasterTrack(0)
for i=R.GetTrackNumSends(master,1)-1,0,-1 do R.RemoveTrackSend(master,1,i) end
assert(R.GetTrackNumSends(master,1)==0)
local item=R.AddMediaItemToTrack(track)
local take=R.AddTakeToMediaItem(item)
R.SetMediaItemTake_Source(take,R.PCM_Source_CreateFromFile(dir..'/demo-A2.wav'))
R.SetMediaItemInfo_Value(item,'D_LENGTH',12)
R.SetMediaItemInfo_Value(item,'D_FADEINLEN',0)
R.SetMediaItemInfo_Value(item,'D_FADEOUTLEN',0)
local fx=R.TrackFX_AddByName(track,'Solo Studio/Solo Studio Strobe.jsfx',false,-1)
assert(fx>=0)
R.TrackFX_SetParam(track,fx,5,1)
R.GetSet_LoopTimeRange2(0,true,true,0,12,false)
R.GetSetRepeat(1)
R.Main_SaveProjectEx(project,dir..'/Tuner preview.rpp',8)
R.TrackFX_Show(track,fx,3)
R.SetEditCurPos2(0,0,false,false)
R.OnPlayButton()
