-- Native integration tests in a silent disposable project; no paid/model calls.
local R=reaper;local root=debug.getinfo(1,'S').source:sub(2):match('^(.*)/Tests/')
local B=dofile(root..'/Scripts/solo_mix_bridge.lua');local State=dofile(root..'/Scripts/solo_mix_state.lua')
local J=B.json;local log=assert(io.open(root..'/Tests/advanced-mix-checks.txt','w'))
local original=R.EnumProjects(-1,'');local before=State.capture(original)
local project,job,s;local passed=0;local command=R.Main_OnCommand
local function check(ok,name)assert(ok,name);passed=passed+1;log:write('PASS '..name..'\n');log:flush()end
local function close(ok,err)
 R.Main_OnCommand=command
 if s and s.probe then pcall(B.cancel_probe,s)end
 if project and R.ValidatePtr(project,'ReaProject*')then
  R.SelectProjectInstance(project);R.OnStopButtonEx(project)
  R.Main_SaveProjectEx(project,job..'/Advanced mix.RPP',8);R.Main_OnCommand(40860,0)
 end
 R.SelectProjectInstance(original)
 log:write(State.capture(original)==before and 'PASS Real project audio state preserved\n'or 'FAIL Real project audio state changed\n')
 log:write(ok and (passed..' advanced native mix checks passed\n')or ('FAIL '..tostring(err)..'\n'));log:close()
 dofile(root..'/Launcher/launch.lua')
end
local task=coroutine.create(function()
 assert(R.GetAllProjectPlayStates()==0,'Stop all transport before testing')
 assert(R.GetExtState('SoloStudio_v1','panel_open')~='1','Close Solo Studio before testing')
 job=root..'/Tests/Advanced mix data/'..R.genGuid():gsub('[^%w]','');R.RecursiveCreateDirectory(job,0)
 local f=assert(io.open(job..'/Advanced mix.RPP','w'));f:write('<REAPER_PROJECT 0.1 7.55 1\n TEMPO 120 4 4\n>\n');f:close()
 R.Main_OnCommand(41929,0);R.Main_openProject(job..'/Advanced mix.RPP');project=R.EnumProjects(-1,'');assert(project~=original)
 local master=R.GetMasterTrack(project)
 for i=R.GetTrackNumSends(master,1)-1,0,-1 do R.RemoveTrackSend(master,1,i)end
 -- A muted hardware send tests restoration without audible output.
 local hardware=R.CreateTrackSend(master,nil);assert(hardware>=0)
 R.SetTrackSendInfo_Value(master,1,hardware,'B_MUTE',1);R.SetTrackSendInfo_Value(master,1,hardware,'D_VOL',.37)
 R.SetMediaTrackInfo_Value(master,'D_VOL',.5)
 R.InsertTrackAtIndex(0,false);local tr=R.GetTrack(project,0);local id=R.GetTrackGUID(tr)
 R.GetSetMediaTrackInfo_String(tr,'P_NAME','Tone source',true);R.SetMediaTrackInfo_Value(tr,'I_RECARM',0)
 R.SetMediaTrackInfo_Value(tr,'D_VOL',.25)
 local item=R.AddMediaItemToTrack(tr);local take=R.AddTakeToMediaItem(item)
 R.SetMediaItemTake_Source(take,assert(R.PCM_Source_CreateFromFile(root..'/Tests/mix-tone.wav')));R.SetMediaItemInfo_Value(item,'D_LENGTH',8)
 local trim=R.TrackFX_AddByName(tr,'Solo Studio/Mix trim.jsfx',false,-1);assert(trim>=0,'Install Mix trim.jsfx');R.TrackFX_SetParam(tr,trim,0,6)
 local trimid=R.TrackFX_GetFXGUID(tr,trim)
 local comp=R.TrackFX_AddByName(tr,'VST: ReaComp (Cockos)',false,-1);assert(comp>=0);R.TrackFX_SetEnabled(tr,comp,false)
 local compid=R.TrackFX_GetFXGUID(tr,comp)
 R.InsertTrackAtIndex(1,false);local dest=R.GetTrack(project,1);local destid=R.GetTrackGUID(dest)
 R.SetMediaTrackInfo_Value(dest,'B_MAINSEND',0)
 local send=R.CreateTrackSend(tr,dest);R.SetTrackSendInfo_Value(tr,0,send,'D_VOL',.1)
 R.SetOnlyTrackSelected(tr)
 s=B.begin(job,{0,8});check(B.inspect(s).capabilities.mix_tools_version==4,'Expanded capabilities exposed')
 local renders={}
 for _,point in ipairs({'pre_fx','post_fx','post_fader'})do
  renders[point]=B.execute(s,'measure_signal',{track=id,point=point})
  check(R.CountTracks(project)==2 and R.GetTrackNumSends(tr,0)==1 and R.IsTrackSelected(tr),'Tap cleanup restores tracks, routing and selection: '..point)
 end
 local cached=B.execute(s,'measure_signal',{track=id,point='pre_fx'})
 check(cached.cached and cached.path==renders.pre_fx.path,'Unchanged signal taps reuse renders')
 renders.mix=B.execute(s,'measure_mix',{});J.write(job..'/signal-results.json',renders)
 R.Main_OnCommand=function(action,...)if action==42230 then error('Injected render failure')end;return command(action,...)end
 local good=pcall(B.execute,s,'measure_signal',{track=id,point='pre_fx',start_seconds=1,duration_seconds=3})
 R.Main_OnCommand=command
 check(not good and R.CountTracks(project)==2 and R.GetTrackNumSends(tr,0)==1 and R.IsTrackSelected(tr),'Failed tap render cleans up temporary routing and selection')
 B.guard(s,true)
 local a=B.execute(s,'save_mix_checkpoint',{name='Starting balance'})
 B.execute(s,'set_master_output',{volume_db=-3})
 B.execute(s,'set_track_mix',{track=id,volume_db=-6,pan=0})
 B.execute(s,'move_effect',{track=id,effect=compid,index=0})
 check(R.TrackFX_GetFXGUID(tr,0)==compid,'Effect order changes by stable GUID')
 B.execute(s,'set_send',{track=id,destination=destid,index=send,volume_db=-10,pan=.25})
 local bus=B.execute(s,'create_mix_bus',{name='Shared room'});local returntrack=B.track(bus.track,project)
 check(R.GetMediaTrackInfo_Value(returntrack,'I_RECINPUT')==-1 and R.GetTrackNumSends(returntrack,1)==0,'New return has no recording input or hardware output')
 local added=B.execute(s,'set_send',{track=id,destination=bus.track,volume_db=-15,mode='post_fader'})
 check(not pcall(B.execute,s,'set_send',{track=bus.track,destination=id,volume_db=-12}),'Feedback loop rejected before creating a send')
 local b=B.execute(s,'save_mix_checkpoint',{name='Alternate balance'})
 B.execute(s,'restore_mix_checkpoint',{id=a.id})
 check(math.abs(R.GetMediaTrackInfo_Value(master,'D_VOL')-.5)<1e-8 and math.abs(R.GetMediaTrackInfo_Value(tr,'D_VOL')-.25)<1e-8,'Checkpoint restores track and master levels')
 check(R.TrackFX_GetFXGUID(tr,0)==trimid and R.GetTrackSendInfo_Value(tr,0,added.index,'B_MUTE')==1 and R.GetMediaTrackInfo_Value(returntrack,'D_VOL')==0,'Earlier checkpoint restores order and silences later send/bus')
 check(math.abs(R.GetTrackSendInfo_Value(tr,0,send,'D_VOL')-.1)<1e-8,'Checkpoint predating a send edit restores its original gain')
 B.execute(s,'restore_mix_checkpoint',{id=b.id})
 check(math.abs(R.GetMediaTrackInfo_Value(master,'D_VOL')-10^(-3/20))<1e-8 and R.GetTrackSendInfo_Value(tr,0,added.index,'B_MUTE')==0,'Later checkpoint restores send and master')
 B.compare(s,'original')
 check(R.TrackFX_GetFXGUID(tr,0)==trimid and math.abs(R.GetMediaTrackInfo_Value(master,'D_VOL')-.5)<1e-8 and R.GetTrackSendInfo_Value(tr,0,added.index,'B_MUTE')==1,'Original restores master, chain order and routing')
 B.compare(s,'candidate')
 check(R.TrackFX_GetFXGUID(tr,0)==compid and math.abs(R.GetMediaTrackInfo_Value(master,'D_VOL')-10^(-3/20))<1e-8,'Candidate restores alternate chain and master')
 B.execute(s,'set_pre_fx_automation',{track=id,points={{seconds=0,db=0},{seconds=1,db=-3},{seconds=7,db=-3},{seconds=8,db=0}}})
 local pre=B.inspect(s).pre_fx_envelopes[1]
 check(pre and R.TrackFX_GetFXGUID(tr,0)==pre.effect and #pre.points==4,'Pre-FX gain envelope is first in the chain with native dB points')
 B.execute(s,'restore_mix_checkpoint',{id=b.id})
 local preidx;for i=0,R.TrackFX_GetCount(tr)-1 do if R.TrackFX_GetFXGUID(tr,i)==pre.effect then preidx=i end end
 check(preidx and not R.TrackFX_GetEnabled(tr,preidx),'Restoring an earlier checkpoint bypasses later added effects')
 -- Updating a checkpoint-bypassed ride must reactivate it.
 B.execute(s,'set_pre_fx_automation',{track=id,points={{seconds=0,db=0},{seconds=1,db=-3},{seconds=7,db=-3},{seconds=8,db=0}}})
 check(R.TrackFX_GetEnabled(tr,0),'Updating a pre-FX ride re-enables its existing processor')
 B.execute(s,'set_effect_state',{track=id,effect=compid,enabled=true})
 B.execute(s,'configure_compressor',{track=id,effect=compid,threshold_db=-40,ratio=4,attack_ms=5,release_ms=100})
 R.SetEditCurPos2(project,5,false,false);R.GetSetRepeatEx(project,1)
 local pending=B.execute(s,'measure_gain_reduction',{effects={{track=id,effect=compid},{track=id,effect=trimid}},start_seconds=0,duration_seconds=3})
 check(pending.pending,'Supported gain-reduction probe starts deferred playback')
 check(R.GetTrackSendInfo_Value(master,1,hardware,'D_VOL')==0,'Probe silences hardware output while leaving processing active')
 local done
 repeat coroutine.yield();done=B.poll_probe(s)until done
 assert(not done.error,done.error);J.write(job..'/gain-reduction.json',done.result)
 check(done.result.effects[1].sample_count>5 and done.result.effects[1].max_db>1,'Actual ReaComp telemetry reports nonzero gain reduction')
 check(not done.result.effects[2].supported,'Unsupported meter is reported as unknown')
 check(R.GetPlayStateEx(project)==0 and R.GetCursorPositionEx(project)==5 and R.GetSetRepeatEx(project,-1)==1,'Probe restores transport, edit cursor and repeat')
 check(math.abs(R.GetTrackSendInfo_Value(master,1,hardware,'D_VOL')-.37)<1e-8,'Successful probe restores hardware output volume')
 B.execute(s,'measure_gain_reduction',{effects={{track=id,effect=compid}},start_seconds=0,duration_seconds=3})
 done=B.poll_probe(s,true)
 check(done.error and not s.probe and R.GetPlayStateEx(project)==0,'Cancelled probe cleans up immediately')
 check(math.abs(R.GetTrackSendInfo_Value(master,1,hardware,'D_VOL')-.37)<1e-8,'Cancelled probe restores hardware volume')
 B.execute(s,'measure_gain_reduction',{effects={{track=id,effect=compid}},start_seconds=0,duration_seconds=3})
 s=B.recover(job)
 check(s and not s.probe and R.GetPlayStateEx(project)==0 and math.abs(R.GetTrackSendInfo_Value(master,1,hardware,'D_VOL')-.37)<1e-8,'Interrupted probe restores outputs from its durable journal')
 s=B.recover(job);check(s and not s.recovery_changed,'Extended journal recovers cleanly after meter cleanup')
 check(B.revert(s)==0,'Full revert has no conflicts')
 check(R.CountTracks(project)==2 and R.TrackFX_GetCount(tr)==2 and R.GetTrackNumSends(tr,0)==1 and math.abs(R.GetTrackSendInfo_Value(tr,0,0,'D_VOL')-.1)<1e-8,'Revert removes owned bus, send and pre-trim while retaining originals')
 check(R.TrackFX_GetFXGUID(tr,0)==trimid and math.abs(R.GetMediaTrackInfo_Value(master,'D_VOL')-.5)<1e-8 and math.abs(R.GetMediaTrackInfo_Value(tr,'D_VOL')-.25)<1e-8,'Revert restores original chain and levels')
 log:write('DATA '..job..'\n');log:flush()
end)
local function tick()
 local ok,err=coroutine.resume(task)
 if not ok then close(false,debug.traceback(task,tostring(err)))
 elseif coroutine.status(task)=='dead'then close(true)
 else R.defer(tick)end
end
tick()
