local root=debug.getinfo(1,'S').source:sub(2):match('^(.*)/Tests/')
local make=dofile(root..'/Scripts/solo_take_selection.lua')
local rows={};for i=1,10 do rows[i]={key=tostring(i),playing=i==1}end
local n=0
local function check(v,label)assert(v,label);n=n+1;print('PASS: '..label)end
local function keys(q,r)local a={};for _,row in ipairs(q.rows(r or rows))do a[#a+1]=row.key end;return table.concat(a,',')end
local q=make();q.sync(rows);q.click(rows,'3',false,false);q.click(rows,'8',false,true)
check(keys(q)=='3,4,5,6,7,8','Shift-click spans offscreen takes using list order')
q.click(rows,'5',false,true)
check(keys(q)=='3,4,5','Repeated Shift-click shrinks the range from its original anchor')
q.click(rows,'1',false,true)
check(keys(q)=='1,2,3','Shift-click also extends backward from the anchor')
q.click(rows,'8',true,false);q.click(rows,'10',true,true)
check(keys(q)=='1,2,3,8,9,10','Cmd-Shift-click adds a range to existing selection')
q.click(rows,'6',false,false)
check(keys(q)=='6','Plain click replaces a multiple selection')
q.click(rows,'6',true,false);q.sync(rows)
check(keys(q)=='','Toggling the final take off stays deselected after refresh')
q.only('5');q.after_delete(rows,{rows[5]})
check(keys(q)=='6','Deleting a middle take selects the next one')
q.only('10');q.after_delete(rows,{rows[9],rows[10]})
check(keys(q)=='8','Deleting the tail selects the nearest previous survivor')
q.only('5');q.after_delete(rows,{rows[4],rows[5],rows[6]})
check(keys(q)=='7','Neighbor selection skips every deleted take')
q.only('5');q.after_delete(rows,rows);q.sync({})
check(keys(q)=='','Deleting all takes leaves selection empty')
q.reset();q.sync(rows);q.click(rows,'4',false,false);q.click(rows,'8',true,false)
q.sync({rows[8],rows[9]})
check(keys(q)=='8','Changing view or section drops hidden selections')
q.reset();q.sync({{key='guitar',playing=true}})
check(keys(q,{{key='guitar'}})=='guitar','Reset scopes selection to the new instrument')
print(n..' take selection checks passed.')
