"""Small, measured evidence charts for model vision. No screenshots or audio uploads."""
import math
from pathlib import Path
import wave

import numpy as np
from charts import plt


def waveform(path, bins=1200):
    """Read our PCM render in bounded chunks; preserve peaks instead of decimating."""
    lows, highs = [], []
    with wave.open(str(path), 'rb') as source:
        channels, width = source.getnchannels(), source.getsampwidth()
        frames, rate = source.getnframes(), source.getframerate()
        if channels not in (1, 2) or width not in (2, 3, 4) or frames < 1:
            raise ValueError('Visual waveform requires mono/stereo PCM audio')
        stride = max(1, math.ceil(frames / bins))
        while True:
            raw = source.readframes(stride * 32)
            if not raw:
                break
            if width == 3:
                b = np.frombuffer(raw, dtype=np.uint8).reshape(-1, 3).astype(np.int32)
                samples = b[:, 0] | (b[:, 1] << 8) | (b[:, 2] << 16)
                samples = (samples ^ 0x800000) - 0x800000
            else:
                samples = np.frombuffer(raw, dtype='<i%d' % width)
            samples = samples.reshape(-1, channels)
            for start in range(0, len(samples), stride):
                block = samples[start:start + stride]
                lows.append(float(block.min()) / 2 ** (width * 8 - 1))
                highs.append(float(block.max()) / 2 ** (width * 8 - 1))
    return np.arange(len(lows)) * stride / rate, np.array(lows), np.array(highs)


def label(value, size=70):
    # User track names remain data; prevent mathtext/line breaks from changing plots.
    return str(value).replace('$', '').replace('\n', ' ').replace('\r', ' ')[:size]


def save(fig, output):
    try:
        # Readers can display the previous complete PNG while its replacement
        # is being generated by the background worker.
        temporary = Path(output).with_suffix('.png.tmp')
        fig.savefig(temporary, dpi=110, format='png')
        temporary.replace(output)
    finally:
        plt.close(fig)
    return Path(output)


def spectral_chart(data, profile, regions, output, perspective=False):
    start, end = profile['measurement_bounds']
    edges = data['time_edges'] + start
    freq = data['frequency_edges']; values = data['dbfs']
    fig = plt.figure(figsize=(12, 6.3), constrained_layout=not perspective)
    if perspective:
        ax = fig.add_axes([.02, .10, .78, .77], projection='3d')
        ax.set_box_aspect((2, 1, .8))
        # Keep the perspective export readable and inexpensive. The heatmap
        # retains every measured time/frequency bucket.
        step = max(1, math.ceil(values.shape[1] / 180))
        times = (edges[:-1] + edges[1:]) / 2
        centers = np.sqrt(freq[:-1] * freq[1:])
        x, y = np.meshgrid(times[::step], np.log10(centers))
        surface = ax.plot_surface(x, y, np.maximum(-90, values[:, ::step]),
                                  cmap='magma', vmin=-90, vmax=0, linewidth=0,
                                  rcount=80, ccount=180, antialiased=False)
        ticks = [value for value in (30, 100, 300, 1000, 3000, 10000, 20000) if freq[0] <= value <= freq[-1]]
        ax.set(yticks=np.log10(ticks), yticklabels=['%g' % t for t in ticks], zlim=(-90, 0),
               zlabel='Band level (dBFS)', xlabel='Project time (seconds)', ylabel='Frequency (Hz, log spacing)')
        ax.view_init(elev=29, azim=-63)
    else:
        ax = fig.add_subplot(111)
        surface = ax.pcolormesh(edges, freq, values, shading='flat', cmap='magma', vmin=-90, vmax=0, rasterized=True)
        ax.set(yscale='log', xlim=(start, end), ylim=(freq[0], freq[-1]),
               xlabel='Project time (seconds)', ylabel='Frequency (Hz)')
        ticks = [value for value in (30, 60, 100, 300, 1000, 3000, 10000, 20000) if freq[0] <= value <= freq[-1]]
        ax.set_yticks(ticks); ax.set_yticklabels(['%g' % t for t in ticks])
        for region in regions[:64]:
            t = region.get('start_seconds', -1)
            if start <= t < end:
                ax.axvline(t, color='white', alpha=.3, linewidth=.7)
                ax.text(t, freq[-1] / 1.1, label(region.get('name', ''), 20), rotation=90,
                        fontsize=7, va='top', color='white')
    if perspective:
        fig.colorbar(surface, cax=fig.add_axes([.88, .22, .018, .58]), label='Log-frequency band power (dBFS)')
    else:
        fig.colorbar(surface, ax=ax, pad=.02, shrink=.8, label='Log-frequency band power (dBFS)')
    scope = 'Solo-in-place · routing, returns and master FX' if profile.get('track') else 'Processed audio'
    fig.suptitle('%s · %s · %.1f–%.1fs\n%s · fixed −90…0 dBFS colors · mean channel power' % (
        label(profile.get('title', 'Measured mix')), 'Spectrum waterfall' if perspective else 'Spectrogram', start, end, scope), fontsize=11)
    return save(fig, output)


def dynamics_chart(profile, output):
    start, end = profile['measurement_bounds']; rows = profile.get('envelope_1s', [])
    fig, axes = plt.subplots(2, 1, figsize=(12, 6.3), sharex=True, constrained_layout=True)
    times = [start + row['seconds'] for row in rows]
    clean = lambda v: v if isinstance(v, (int, float)) and math.isfinite(v) else float('nan')
    for key, title, color in [('rms_dbfs', 'RMS (1s)', '#287eab'), ('peak_dbfs', 'Sample peak (1s)', '#d28b21')]:
        axes[0].plot(times, [clean(row.get(key)) for row in rows], label=title, color=color)
    axes[0].set(ylabel='dBFS', ylim=(-72, 3), title='Processed level over time · gaps remain visible')
    axes[1].plot(times, [clean(row.get('crest_db')) for row in rows], color='#9266a9', label='Peak minus RMS (1s)')
    axes[1].set(xlim=(start, end), ylim=(0, 30), xlabel='Project time (seconds)', ylabel='Crest (dB)',
                title='Transient crest · context for dynamics, not measured limiter gain reduction')
    for ax in axes: ax.grid(alpha=.2); ax.legend(fontsize=8)
    loudness = profile.get('loudness', {})
    scope = 'Solo-in-place: routing, returns and master FX' if profile.get('track') else 'Last measured audio'
    fig.suptitle('%s · %s LUFS · %s dBTP · %s LU LRA\n%s; this chart does not measure plugin gain reduction' % (
        label(profile.get('title', 'Measured mix')), loudness.get('integrated_lufs'),
        loudness.get('true_peak_dbtp'), loudness.get('loudness_range_lu'), scope), fontsize=11)
    return save(fig, output)


def mix_graphics(path, profile, regions, folder):
    from spectrogram import spectrum_over_time
    folder = Path(folder); folder.mkdir(exist_ok=True)
    stem = Path(path).stem + '-v1'
    files = {key: stem + '-' + key + '.png' for key in ('spectrogram', 'waterfall', 'dynamics')}
    if any(not (folder / files[key]).exists() for key in ('spectrogram', 'waterfall')):
        data = spectrum_over_time(path)
        for key in ('spectrogram', 'waterfall'):
            if not (folder / files[key]).exists():
                spectral_chart(data, profile, regions, folder / files[key], perspective=key == 'waterfall')
    if not (folder / files['dynamics']).exists(): dynamics_chart(profile, folder / files['dynamics'])
    return {'version': 1, 'render': Path(path).name, 'measurement_bounds': profile['measurement_bounds'],
            'title': profile.get('title', 'Measured mix'), 'views': files}


def level_curve_chart(plan, output):
    """Measured moving RMS and a clearly labeled, unrendered automation preview."""
    fig, axes = plt.subplots(2, 1, figsize=(12, 6), sharex=True, constrained_layout=True)
    rows = [row for row in plan['curve'] if 'rms_dbfs' in row]
    x = [row['seconds'] for row in rows]
    clean = lambda value: value if isinstance(value, (int, float)) and math.isfinite(value) else float('nan')
    axes[0].plot(x, [clean(row.get('peak_dbfs')) for row in rows], color='#999999', alpha=.6, label='Measured 1s peak')
    axes[0].plot(x, [clean(row.get('smoothed_rms_dbfs')) for row in rows], color='#287eab', label='Measured moving RMS')
    axes[0].plot(x, [row['smoothed_rms_dbfs'] + row['applied_correction_db'] if row['active'] else float('nan')
                     for row in rows], color='#d28b21', label='Predicted moving RMS (linear estimate)')
    axes[0].axhline(plan['target_smoothed_rms_dbfs'], color='#777777', linestyle=':', linewidth=.8, label='Full-performance median')
    axes[0].set(ylabel='dBFS', title='Activity-gated level preview · gaps excluded from target')
    axes[1].plot([row['seconds'] for row in plan['curve']], [row['applied_correction_db'] for row in plan['curve']],
                 color='#9266a9', label='New correction only')
    axes[1].plot([p['seconds'] for p in plan['points']], [p['db'] for p in plan['points']],
                 color='#287eab', alpha=.65, label='Resulting owned trim (includes earlier rides)')
    axes[1].axhline(0, color='#777777', linewidth=.8)
    axes[1].set(xlim=plan['range'], xlabel='Project time (seconds)', ylabel='Gain (dB)')
    for ax in axes:
        ax.grid(alpha=.2); ax.legend(fontsize=8, loc='best')
    fig.suptitle('%s · %.0f%% strength · %.1fs smoothing\nActive p90–p10 spread %.1f → %.1f dB predicted · verify actual render after applying' % (
        label(plan.get('name', 'Level automation')), plan['strength'] * 100, plan['window_seconds'],
        plan['before_spread_db'], plan['predicted_spread_db']), fontsize=10)
    return save(fig, output)


def arrangement_chart(data, output):
    rows = data['tracks']; start, end = data['bounds']
    fig, axes = plt.subplots(len(rows), 1, figsize=(12, max(3, len(rows) * .46 + 1.4)),
                             sharex=True, squeeze=False, constrained_layout=True)
    for row, ax in zip(rows, axes[:, 0]):
        values = np.asarray(row['peaks'], dtype=float)
        maximum = float(values.max()) if len(values) else 0
        x = np.linspace(start, end, len(values), endpoint=False)
        color = '#999999' if row['muted'] else '#287eab'
        if maximum > 0:
            ax.fill_between(x, -values / maximum, values / maximum, color=color, linewidth=0)
        for clip in row['clips']:
            if clip['kind'] not in ('audio',):
                ax.axvspan(clip['start_seconds'], clip['end_seconds'], alpha=.2,
                           color='#ca982c' if clip['kind'] == 'midi' else '#c64747')
        flags = (' [muted]' if row['muted'] else '')
        if row['midi']: flags += ' [MIDI]'
        if row['unavailable']: flags += ' [peaks unavailable]'
        if row['truncated']: flags += ' [partial overview]'
        if not row['clips']: flags += ' [no active items; may be a bus]'
        ax.set_ylabel(label(row['name'] + flags, 60), rotation=0, ha='right', va='center', fontsize=8)
        ax.set_ylim(-1.1, 1.1); ax.set_yticks([]); ax.grid(axis='x', alpha=.2)
    axes[-1, 0].set(xlim=(start, end), xlabel='Project time (seconds)')
    first = data['start_track'] + 1
    fig.suptitle('Source clips · tracks %d–%d of %d\n'
                 'Each track scaled independently · NOT processed mix levels · '
                 'Gold: MIDI · Red: unavailable peaks%s' % (
                     first, first + len(rows) - 1, data['total_tracks'],
                     ' · Overview incomplete' if data['truncated'] else ''), fontsize=10)
    return save(fig, output)


def processed_chart(path, profile, references, regions, output):
    start, end = profile['measurement_bounds']
    x, low, high = waveform(path)
    fig, axes = plt.subplots(2, 2, figsize=(12, 7.3), constrained_layout=True)
    axes[0, 0].fill_between(x + start, low, high, color='#287eab', linewidth=0)
    axes[0, 0].set(title='Processed waveform · channel peak envelope',
                   xlabel='Project time (seconds)', ylabel='Amplitude (full scale = ±1)',
                   ylim=(-1.05, 1.05), xlim=(start, end))
    env = profile.get('envelope_1s', [])
    for key, name, color in [('rms_dbfs', 'RMS', '#287eab'), ('peak_dbfs', 'Peak', '#d28b21')]:
        axes[0, 1].plot([start + p['seconds'] for p in env],
                        [p.get(key) if p.get(key) is not None else float('nan') for p in env],
                        color=color, label=name)
    axes[0, 1].set(title='Processed level envelope', xlabel='Project time (seconds)',
                   ylabel='dBFS', ylim=(-72, 3), xlim=(start, end))
    axes[0, 1].legend(fontsize=8)
    for region in regions[:64]:
        t = region.get('start_seconds', -1)
        if start < t < end:
            for ax in axes[0]: ax.axvline(t, color='#777777', alpha=.3, linewidth=.6)
            axes[0, 0].text(t, .98, label(region.get('name', ''), 18), rotation=90,
                            fontsize=6, va='top', color='#555555')
    curves = [(profile, '#287eab')] + list(zip(references[:2], ['#d28b21', '#9266a9']))
    for row, color in curves:
        spectrum = row.get('spectrum', [])
        axes[1, 0].semilogx([(b['low_hz'] * b['high_hz']) ** .5 for b in spectrum],
                            [b['relative_db'] for b in spectrum], color=color,
                            label=label(row.get('title', 'Reference'), 42))
        bands = row.get('bands', [])
        axes[1, 1].plot([(b['low_hz'] * b['high_hz']) ** .5 for b in bands],
                        [100 * b['side_fraction'] if b.get('side_fraction') is not None else float('nan') for b in bands],
                        color=color)
    axes[1, 0].set(title='Tonal distribution · independently level-normalized',
                   xlabel='Frequency (Hz)', ylabel='Relative band energy (dB)', xlim=(20, 20000))
    axes[1, 0].legend(fontsize=8)
    axes[1, 1].set(title='Stereo side energy by band', xlabel='Frequency (Hz)',
                   ylabel='Side energy (%)', xscale='log', xlim=(20, 20000), ylim=(0, 100))
    for ax in axes.flat: ax.grid(alpha=.2)
    loudness = profile['loudness']
    def metric(value):
        return '—' if value is None else '%.1f' % value
    fig.suptitle('%s · %s · %.1f–%.1fs\n%s LUFS · %s dBTP · %s LU LRA · %s dB crest\n%s' % (
        label(profile['title']), 'Full selected passage' if profile['measurement_kind']=='full_passage' else 'Diagnostic window', start, end,
        metric(loudness.get('integrated_lufs')), metric(loudness.get('true_peak_dbtp')),
        metric(loudness.get('loudness_range_lu')), metric(profile.get('crest_db')),
        label(profile.get('scope', 'Full mix through routing and master FX'), 110)), fontsize=10)
    return save(fig, output)
